// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual Web API key
    appId: '1:213103035946:web:8bd66f987a308cad222553',
    messagingSenderId: '213103035946',
    projectId: 'mindup-app-213103035946', // Using your actual project ID
    authDomain: 'mindup-app-213103035946.firebaseapp.com',
    storageBucket: 'mindup-app-213103035946.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual Android API key
    appId: '1:213103035946:android:c193c8f6ac8c785e222553',
    messagingSenderId: '213103035946',
    projectId: 'mindup-app-213103035946', // Using your actual project ID
    storageBucket: 'mindup-app-213103035946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual iOS API key
    appId: '1:213103035946:ios:f6b4d7c96c8b3f57222553',
    messagingSenderId: '213103035946',
    projectId: 'mindup-app-213103035946', // Using your actual project ID
    storageBucket: 'mindup-app-213103035946.appspot.com',
    iosBundleId: 'com.example.stress_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual macOS API key
    appId: '1:213103035946:ios:f6b4d7c96c8b3f57222553',
    messagingSenderId: '213103035946',
    projectId: 'mindup-app-213103035946', // Using your actual project ID
    storageBucket: 'mindup-app-213103035946.appspot.com',
    iosBundleId: 'com.example.stress_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:
        'AIzaSyExxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual Windows API key
    appId: '1:213103035946:web:3e148b86be2a4de1222553',
    messagingSenderId: '213103035946',
    projectId: 'mindup-app-213103035946', // Using your actual project ID
    authDomain: 'mindup-app-213103035946.firebaseapp.com',
    storageBucket: 'mindup-app-213103035946.appspot.com',
  );
}
